version: '2.2'
services:
  redis:
    image: redis:6.0.6
    restart: always
    command: ["redis-server", "--requirepass", "${RCTF_REDIS_PASSWORD}"]
    volumes:
      - ./data/rctf-redis:/data
    ports:
    - 127.0.0.1:6379:6379
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data/rctf-postgres:/var/lib/postgresql/data